// Generated by CoffeeScript 1.8.0
(function() {
  this.MenuLayer = cc.Layer.extend({
    ctor: function() {
      return this._super();
    },
    init: function() {
      var centerpos, menu, menuItemPlay, spritebg, winsize;
      this._super();
      winsize = cc.director.getWinSize();
      centerpos = cc.p(winsize.width / 2, winsize.height / 2);
      spritebg = new cc.Sprite(res.helloBG_png);
      spritebg.setPosition(centerpos);
      this.addChild(spritebg);
      cc.MenuItemFont.setFontSize(60);
      menuItemPlay = cc.MenuItemSprite.create(new cc.Sprite(res.start_n_png), new cc.Sprite(res.start_s_png), this.onPlay, this);
      menu = new cc.Menu(menuItemPlay);
      menu.setPosition(centerpos);
      return this.addChild(menu);
    },
    onPlay: function() {
      cc.log("==onplay clicked");
      return cc.director.runScene(new PlayScene());
    }
  });

  this.MenuScene = cc.Scene.extend({
    onEnter: function() {
      var layer;
      this._super();
      layer = new MenuLayer();
      layer.init();
      return this.addChild(layer);
    }
  });

}).call(this);
