// Generated by CoffeeScript 1.8.0
(function() {
  this.abstract = {};

  this.shapes = {};

  this.guiElements = {};

  this.layers = {};

  this.scenes = {};

  this.data = {};

  this.musicengine = {};

}).call(this);
