// Generated by CoffeeScript 1.8.0
(function() {
  this.layers.AnimationLayer = cc.Layer.extend({
    ctor: function() {
      this._super();
      return this.init();
    },
    init: function() {
      var actionTo, spriteRunner;
      this._super();
      spriteRunner = new cc.Sprite(res.runner_png);
      spriteRunner.attr({
        x: 80,
        y: 85
      });
      actionTo = new cc.MoveTo(2, cc.p(300, 85));
      spriteRunner.runAction(new cc.Sequence(actionTo));
      return this.addChild(spriteRunner);
    }
  });

}).call(this);
